name: fl_amap
description: AMap location plugin for flutter, supports single positioning and continuous positioning
version: 2.5.2
repository: https://github.com/Wayaer/fl_amap/tree/main/fl_amap

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: fl.amap
        pluginClass: AMapPlugin
      ios:
        pluginClass: AMapPlugin
